name: Secretlint

on:
  pull_request:
  push:
    branches: main

jobs:
  secretlint:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          package_json_file: package.json
      - run: pnpx @secretlint/quick-start "**/*"
